# Generated by Django 4.2.12 on 2024-05-09 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id_history", models.IntegerField(primary_key=True, serialize=False)),
                ("number_doc", models.IntegerField()),
                ("last_name", models.CharField(max_length=60)),
                ("surname", models.CharField(max_length=60)),
                ("first_name", models.CharField(max_length=60)),
                ("middle_name", models.CharField(max_length=60)),
                ("date_born", models.DateField(max_length=16)),
                (
                    "biologic_sex",
                    models.CharField(
                        choices=[
                            ("01", "Hombre"),
                            ("02", "Mujer"),
                            ("03", "Indeterminado intersexual"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "gender_identity",
                    models.CharField(
                        choices=[
                            ("01", "Masculino"),
                            ("02", "Femenino"),
                            ("03", "Transgenero"),
                            ("04", "Neutro"),
                            ("05", "No lo declara"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "opossition_donation",
                    models.CharField(
                        choices=[("01", "Si"), ("02", "No")], default="01", max_length=2
                    ),
                ),
                ("date_opossition", models.DateField(max_length=10)),
                (
                    "antiquated_will_document",
                    models.CharField(
                        choices=[("01", "Si"), ("02", "No")], default="01", max_length=2
                    ),
                ),
                ("date_suscrip_ant_will_doc", models.DateField(max_length=10)),
                ("cod_borrower", models.CharField(max_length=12)),
                (
                    "territorial_zone",
                    models.CharField(
                        choices=[("01", "Urbana"), ("02", "Rural")],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "category_disability",
                    models.ForeignKey(
                        db_column="id_dis",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.disability",
                    ),
                ),
                (
                    "country_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons_from_country",
                        to="clinica.countries",
                    ),
                ),
                (
                    "doc_type",
                    models.ForeignKey(
                        db_column="id_typedoc",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.typesdocs",
                    ),
                ),
                (
                    "eps",
                    models.ForeignKey(
                        db_column="code_eps",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.eps",
                    ),
                ),
                (
                    "ethnicity",
                    models.ForeignKey(
                        db_column="id_et",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.ethnicity",
                    ),
                ),
                (
                    "habitual_residence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons_living_in_country",
                        to="clinica.countries",
                    ),
                ),
                (
                    "municipality_of_hab_res",
                    models.ForeignKey(
                        db_column="code_dep",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.municipalities",
                    ),
                ),
                (
                    "occupation_care",
                    models.ForeignKey(
                        db_column="code_occ",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.occupations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactWithHealthService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start_attention", models.DateField(max_length=16)),
                (
                    "it_groups",
                    models.CharField(
                        choices=[
                            ("01", "Consulta Externa"),
                            ("02", "Apoyo Diagnostico y Complementacion Terapeutica"),
                            ("03", "Internacion"),
                            ("04", "Quirurgico"),
                            ("05", "Atencion Inmediata"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "env_attention",
                    models.CharField(
                        choices=[
                            ("01", "Hogar"),
                            ("02", "Comunitario"),
                            ("03", "Escolar"),
                            ("04", "Laboral"),
                            ("05", "Institucional"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                ("date_triage", models.DateField(max_length=16)),
                (
                    "classification_triage",
                    models.CharField(
                        choices=[
                            ("01", "TRIAGE I"),
                            ("02", "TRIAGE II"),
                            ("03", "TRIAGE III"),
                            ("04", "TRIAGE IV"),
                            ("05", "TRIAGE V"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "type_of_diagnosis",
                    models.CharField(
                        choices=[
                            ("01", "Impresión Diagnóstica"),
                            ("02", "Confirmado Nuevo"),
                            ("03", "Confirmado Repetido"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "cause_of_care",
                    models.ForeignKey(
                        db_column="id_care",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.causecare",
                    ),
                ),
                (
                    "cod_borr",
                    models.ForeignKey(
                        db_column="code_borrow",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.borrows",
                    ),
                ),
                (
                    "diagnosis_of_admission",
                    models.ForeignKey(
                        db_column="cod_4",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.illnesses",
                    ),
                ),
                (
                    "id_history",
                    models.ForeignKey(
                        db_column="id_history",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.person",
                    ),
                ),
                (
                    "modality_of_realization_it",
                    models.ForeignKey(
                        db_column="id_typemod",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.modality",
                    ),
                ),
                (
                    "way_of_entry",
                    models.ForeignKey(
                        db_column="id_type_entrys",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinica.entrys",
                    ),
                ),
            ],
        ),
    ]
