# Generated by Django 4.2.12 on 2024-05-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0002_person_contactwithhealthservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id_history",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
