# Generated by Django 3.2.8 on 2024-05-15 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_person_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number_doc',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten números', regex='^[3-20]*$')], verbose_name='Número de documento persona'),
        ),
    ]
